# Generated by Django 4.2.3 on 2023-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
            ],
        ),
    ]
