# Generated by Django 4.2.3 on 2023-07-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_members_options_alter_members_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
