# Generated by Django 4.2.3 on 2023-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_members_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="members",
            name="nickname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
